services:
  db:
    image: mysql/mysql-server:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/script.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    networks:
      - node-network

  app:
    build: ./docker/node
    image: rodrigoborgs/node
    container_name: app
    restart: always
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app/src:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge